import './globals.css';
import { Inter } from 'next/font/google';
import styles from './layout.module.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <div className={styles.title}>
            <h1>BeTBeT</h1>
            <h2>Ставки на спорт</h2>
            <h6>почти легально</h6>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
